import { writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { BaseAgentBackend } from '../../../src/main/agents/base-backend'
import { agentSaveWork, createWork } from '../../../src/main/folio/works'
import { workPreview } from '../../../src/shared/work-preview'
import type { AgentBackend, PermissionResponder, RunHandle } from '../../../src/main/agents/agent-backend'
import type {
  AgentId,
  AgentMetadata,
  NormalizedEvent,
  PlanDescriptor,
  PluginCommandsResult,
  PromptOptions,
  SessionRunInput,
  SessionMeta,
  UsageData,
} from '../../../src/shared/types'
import type { SessionLoadMessage } from '../../../src/shared/session-history'

const MOCK_SESSION_ID = 'mock-session-001'
const MOCK_PLAN_TOOL_USE_ID = 'mock-plan-tool-001'
const MOCK_PLAN_CONTENT = `# Implementation Plan

## Overview
This is a mock plan for testing purposes.

## Steps
1. Set up the project structure
2. Implement the core feature
3. Write tests
4. Deploy

## Notes
- This plan was generated by the test mock backend
- All steps should be completed in order
`

const MOCK_METADATA: AgentMetadata = {
  id: 'claude-code',
  label: 'Claude Code (Mock)',
  models: [{ id: 'mock-model', label: 'Mock Model' }],
  defaultModel: 'mock-model',
}

export class MockAgentBackend extends BaseAgentBackend implements AgentBackend {
  readonly id: AgentId = 'claude-code'
  readonly metadata: AgentMetadata = MOCK_METADATA
  readonly permissions: PermissionResponder

  private permissionSeq = 0
  private pendingPermissions = new Map<string, { handle: RunHandle; sessionId: string | null; workUpdate?: { workId: string; title: string; docType: 'doc' | 'slides' | 'diagram'; content: string } }>()

  /** Override per-test via mockResponses map: prompt substring → response text */
  static responses = new Map<string, string>([
    // NOTE: trigger keyword avoids markdown-special chars (e.g. `_`) because the
    // chat input is a markdown editor that escapes them on serialize, which would
    // stop the typed prompt from matching this key.
    ['MOCKMARKDOWN', '**Bold text** and _italic_ text.\n\n## Heading\n\nA paragraph with `code` inside.'],
    ['', 'This is a mock response from the test agent.'],
  ])

  constructor() {
    super()
    this.permissions = {
      getPendingInfo: (questionId) => {
        const pending = this.pendingPermissions.get(questionId)
        return pending ? { toolName: 'Bash', sessionId: pending.sessionId } : undefined
      },
      respondToPermission: (questionId, decision) => this._respondToPermission(questionId, decision),
      respondToQuestion: () => false,
      clearPendingForSession: (sessionId) => {
        for (const [questionId, pending] of this.pendingPermissions) {
          if (pending.sessionId === sessionId) this.pendingPermissions.delete(questionId)
        }
      },
      setCurrentSessionId: () => {},
    }
  }

  startRun(input: SessionRunInput, options: PromptOptions): RunHandle {
    let _resolveRun!: () => void
    let _rejectRun!: (err: Error) => void
    const runPromise = new Promise<void>((res, rej) => { _resolveRun = res; _rejectRun = rej })

    const handle: RunHandle = {
      sessionId: null,
      tabId: input.tabId,
      startedAt: Date.now(),
      toolCallCount: 0,
      sawPermissionRequest: false,
      permissionDenials: [],
      abortController: new AbortController(),
      runPromise,
      _resolveRun,
      _rejectRun,
    }
    this.pendingRuns.push(handle)

    // Emit events asynchronously so the caller can register listeners first.
    setImmediate(() => this._emitConversation(handle, options))

    return handle
  }

  private _emitConversation(handle: RunHandle, options: PromptOptions) {
    if (handle.abortController.signal.aborted) return

    // The chat input is a markdown editor that backslash-escapes underscores on
    // serialize (e.g. `__MOCK_DOCUMENT__` → `\__MOCK_DOCUMENT_\_`). Strip the
    // escapes so the literal trigger strings below (and in specs) still match.
    const prompt = (typeof options.prompt === 'string' ? options.prompt : '').replace(/\\/g, '')
    const responseText = this._responseFor(prompt)

    this.promoteToActive(handle, MOCK_SESSION_ID)

    this.emit('normalized', MOCK_SESSION_ID, {
      type: 'session_init',
      sessionId: MOCK_SESSION_ID,
      model: 'mock-model',
      skills: [],
    } satisfies NormalizedEvent)

    // Emit a plan event for plan-triggering prompts.
    if (prompt.includes('__MOCK_PLAN__')) {
      this.emit('normalized', MOCK_SESSION_ID, {
        type: 'plan',
        planContent: MOCK_PLAN_CONTENT,
        planFilePath: '',
        questionId: '',
        options: [],
        planToolUseId: MOCK_PLAN_TOOL_USE_ID,
      } satisfies NormalizedEvent)
    }

    // Drive a create_work tool call (skeleton card → persist → work_created)
    // for document-triggering prompts. Fixed id so __MOCK_WORK_UPDATE__ targets it.
    // The _SLOW_ variant paces chunks so the generating-skeleton phase is observable.
    if (prompt.includes('__MOCK_DOCUMENT__') || prompt.includes('__MOCK_DOCUMENT_SLOW__')) {
      void this._streamCreateWork(handle, {
        workId: 'mock-work-001',
        title: 'Mock Test Document',
        docType: 'doc',
        content: '# Mock Test Document\n\nThis is a test document created by the mock agent.',
        completion: 'Created the document.',
        slow: prompt.includes('__MOCK_DOCUMENT_SLOW__'),
      })
      return
    }

    // Same streaming create flow for diagrams.
    if (prompt.includes('__MOCK_DIAGRAM__')) {
      void this._streamCreateWork(handle, {
        workId: 'mock-diagram-001',
        title: 'Mock Architecture',
        docType: 'diagram',
        content: JSON.stringify({
          nodes: [
            { id: 'web', label: 'Web Client', icon: 'client' },
            { id: 'api', label: 'API Server', icon: 'service' },
            { id: 'db', label: 'Database', icon: 'logos:postgresql' },
            // Pre-built subflow: a sized group with one child nested inside it,
            // so the subflow nesting/detach e2e tests don't depend on flaky
            // drag math. Explicit positions keep the pair deterministic.
            {
              id: 'cluster',
              label: 'Kubernetes',
              icon: 'logos:kubernetes',
              group: true,
              position: { x: 120, y: 420 },
              width: 320,
              height: 220,
            },
            {
              id: 'worker',
              label: 'Worker',
              icon: 'service',
              parentId: 'cluster',
              position: { x: 40, y: 80 },
            },
          ],
          edges: [
            { id: 'e1', source: 'web', target: 'api', label: 'HTTPS' },
            { id: 'e2', source: 'api', target: 'db', label: 'SQL' },
          ],
        }),
        completion: 'Created the diagram.',
      })
      return
    }

    // Drive a render_artifact call (skeleton → artifact_created). The HTML carries
    // an <input> so the expand-without-reload test can prove state survives.
    if (prompt.includes('__MOCK_ARTIFACT_HTML__')) {
      void this._emitArtifact(handle, {
        kind: 'html',
        html: '<!doctype html><html><body style="margin:0;padding:24px;font-family:sans-serif">'
          + '<h2>Interactive artifact</h2><input id="v" data-testid="artifact-input" value="0" />'
          + '</body></html>',
        completion: 'Rendered the interactive artifact.',
      })
      return
    }

    if (prompt.includes('__MOCK_ARTIFACT_IMAGE__')) {
      // A 1x1 transparent PNG written to a temp file so the solus-artifact
      // protocol has a real file to stream.
      const pngBytes = Buffer.from(
        'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAC0lEQVR42mNk+P+/HgAFhAJ/wlseKgAAAABJRU5ErkJggg==',
        'base64',
      )
      const filePath = join(tmpdir(), 'mock-artifact.png')
      writeFileSync(filePath, pngBytes)
      void this._emitArtifact(handle, {
        kind: 'image',
        path: filePath,
        completion: 'Rendered the image.',
      })
      return
    }

    // Emit a work_updated event (agent revised an existing work in place).
    // Persist via agentSaveWork so a "previous version" snapshot exists for the
    // revision-diff ("View changes"), mirroring the real update_work path.
    if (prompt.includes('__MOCK_WORK_UPDATE__')) {
      const content = '# Mock Test Document (updated)\n\nThe agent revised this document in place.'
      void agentSaveWork('mock-work-001', { content, preview: workPreview('doc', content) })
        .catch(() => {})
        .then(() => {
          this.emit('normalized', MOCK_SESSION_ID, {
            type: 'work_updated',
            workId: 'mock-work-001',
            title: 'Mock Test Document',
            docType: 'doc',
            content,
            updatedAt: new Date().toISOString(),
          } satisfies NormalizedEvent)
          this._completeRun(handle, 'Updated the document.')
        })
      return
    }

    // Emit an update_work permission request; on approve, emit work_updated.
    if (prompt.includes('__MOCK_WORK_TOOL_PERMISSION__')) {
      const questionId = `mock-permission-q-${++this.permissionSeq}`
      this.pendingPermissions.set(questionId, {
        handle,
        sessionId: MOCK_SESSION_ID,
        workUpdate: {
          workId: 'mock-work-001',
          title: 'Mock Test Document',
          docType: 'doc',
          content: '# Mock Test Document (agent-updated)\n\nApproved via permission prompt.',
        },
      })
      this.emit('normalized', MOCK_SESSION_ID, {
        type: 'permission_request',
        questionId,
        toolName: 'mcp__solus-works__update_work',
        toolDescription: 'Update a work the user has open',
        toolInput: { work_id: 'mock-work-001' },
        options: [
          { id: 'allow', kind: 'allow', label: 'Allow' },
          { id: 'deny', kind: 'deny', label: 'Deny' },
        ],
      } satisfies NormalizedEvent)
      return
    }

    // Emit a rate limit event for rate-limit-triggering prompts.
    if (prompt.includes('__MOCK_RATE_LIMIT__')) {
      this.emit('normalized', MOCK_SESSION_ID, {
        type: 'rate_limit',
        status: 'paused',
        resetsAt: Math.floor(Date.now() / 1000) + 300,
        rateLimitType: 'output_tokens',
        isUsingOverage: false,
      } satisfies NormalizedEvent)
      // Don't emit exit — the session stays rate_limited until the user acts.
      this.activeRuns.delete(MOCK_SESSION_ID)
      return
    }

    // Emit a permission request for permission-triggering prompts.
    if (prompt.includes('__MOCK_PERMISSION__')) {
      const questionId = `mock-permission-q-${++this.permissionSeq}`
      this.pendingPermissions.set(questionId, { handle, sessionId: MOCK_SESSION_ID })
      this.emit('normalized', MOCK_SESSION_ID, {
        type: 'permission_request',
        questionId,
        toolName: 'Bash',
        toolDescription: 'Run a shell command',
        toolInput: { command: 'echo test' },
        options: [
          { id: 'allow', kind: 'allow', label: 'Allow' },
          { id: 'deny', kind: 'deny', label: 'Deny' },
        ],
      } satisfies NormalizedEvent)
      // Pause here — control-plane will set status to awaiting_input.
      return
    }

    // Report token usage for the context meter.
    if (prompt.includes('__MOCK_USAGE__')) {
      this._completeRun(handle, responseText, [], {
        inputTokens: 50_000,
        outputTokens: 1_200,
        cacheReadTokens: 10_000,
        cacheCreationTokens: 0,
      })
      return
    }

    this._completeRun(handle, responseText)
  }

  /** Drive the full create_work path: a tool call whose input arrives in chunks
   *  (pacing the generating-skeleton phase), then persistence, then work_created
   *  to finalize. Mirrors the real Claude/Codex create flow. */
  private async _streamCreateWork(
    handle: RunHandle,
    opts: { workId: string; title: string; docType: 'doc' | 'slides' | 'diagram'; content: string; completion: string; slow?: boolean },
  ): Promise<void> {
    if (handle.abortController.signal.aborted) return
    const pace = () => (opts.slow ? new Promise((r) => setTimeout(r, 100)) : Promise.resolve())

    const toolId = `mock-create-${opts.workId}`
    this.emit('normalized', MOCK_SESSION_ID, {
      type: 'tool_call',
      toolName: 'mcp__solus-works__create_work',
      toolId,
      index: 0,
    } satisfies NormalizedEvent)

    // Pace the running phase in a few steps so _SLOW_ keeps the skeleton up; the
    // full tool input now lands on completion, mirroring the real Claude/Codex flow.
    const inputJson = JSON.stringify({ title: opts.title, doc_type: opts.docType, content: opts.content })
    for (let i = 0; i < 4; i++) {
      if (handle.abortController.signal.aborted) return
      await pace()
    }
    this.emit('normalized', MOCK_SESSION_ID, { type: 'tool_call_complete', index: 0, toolId, toolInput: inputJson } satisfies NormalizedEvent)
    await pace()

    // Persist under the fixed id so later update_work calls target the same work.
    await createWork(opts.title, opts.docType, opts.content, workPreview(opts.docType, opts.content), MOCK_SESSION_ID, 'claude-code', '~', opts.workId).catch(() => {})

    this.emit('normalized', MOCK_SESSION_ID, {
      type: 'work_created',
      workId: opts.workId,
      title: opts.title,
      docType: opts.docType,
      content: opts.content,
    } satisfies NormalizedEvent)

    this._completeRun(handle, opts.completion)
  }

  /** Drive the render_artifact path: a tool call (provisional skeleton), then
   *  artifact_created to finalize, mirroring the real Claude/Codex flow. */
  private async _emitArtifact(
    handle: RunHandle,
    opts: { kind: 'html' | 'image'; html?: string; path?: string; completion: string },
  ): Promise<void> {
    if (handle.abortController.signal.aborted) return

    this.emit('normalized', MOCK_SESSION_ID, {
      type: 'tool_call',
      toolName: 'mcp__solus__render_artifact',
      toolId: 'mock-artifact-call',
      index: 0,
    } satisfies NormalizedEvent)

    this.emit('normalized', MOCK_SESSION_ID, {
      type: 'artifact_created',
      kind: opts.kind,
      html: opts.html,
      path: opts.path,
    } satisfies NormalizedEvent)

    this._completeRun(handle, opts.completion)
  }

  private _respondToPermission(questionId: string, decision: string): boolean {
    const pending = this.pendingPermissions.get(questionId)
    if (!pending) return false

    this.pendingPermissions.delete(questionId)
    const sessionId = pending.sessionId ?? MOCK_SESSION_ID
    const denied = decision === 'deny'

    this.emit('normalized', sessionId, {
      type: 'permission_resolved',
      questionId,
    } satisfies NormalizedEvent)

    if (!denied && pending.workUpdate) {
      this.emit('normalized', sessionId, {
        type: 'work_updated',
        workId: pending.workUpdate.workId,
        title: pending.workUpdate.title,
        docType: pending.workUpdate.docType,
        content: pending.workUpdate.content,
        updatedAt: new Date().toISOString(),
      } satisfies NormalizedEvent)
    }

    this._completeRun(
      pending.handle,
      denied
        ? 'Permission denied. The mock test agent completed without running the command.'
        : 'Permission approved. The mock test agent completed after running the command.',
      denied ? [{ toolName: 'Bash', toolUseId: questionId }] : [],
    )

    return true
  }

  private _completeRun(
    handle: RunHandle,
    responseText: string,
    permissionDenials: Array<{ toolName: string; toolUseId: string }> = [],
    usage: UsageData = {},
  ) {
    if (handle.abortController.signal.aborted) return

    const sessionId = handle.sessionId ?? MOCK_SESSION_ID

    // Stream the response in word-sized chunks to exercise the text_chunk path.
    const words = responseText.split(' ')
    for (let i = 0; i < words.length; i++) {
      if (handle.abortController.signal.aborted) break
      this.emit('normalized', sessionId, {
        type: 'text_chunk',
        text: (i === 0 ? '' : ' ') + words[i],
      } satisfies NormalizedEvent)
    }

    this.emit('normalized', MOCK_SESSION_ID, {
      type: 'task_complete',
      result: responseText,
      costUsd: 0,
      durationMs: 10,
      numTurns: 1,
      usage,
      sessionId,
      permissionDenials,
    } satisfies NormalizedEvent)

    handle._resolveRun()
    this.emit('exit', sessionId, 0, null)
    this.activeRuns.delete(sessionId)
    this.finishedRuns.set(sessionId, handle)
    setTimeout(() => this.finishedRuns.delete(sessionId), 5000)
  }

  private _responseFor(prompt: string): string {
    for (const [key, value] of MockAgentBackend.responses) {
      if (key === '' || prompt.toLowerCase().includes(key.toLowerCase())) {
        return value
      }
    }
    return 'Mock response.'
  }

  protected override _errorMessage(_exitCode: number | null): string {
    return 'Mock error'
  }

  async listSessions(_projectPath: string): Promise<SessionMeta[]> {
    return []
  }

  async loadSession(_sessionId: string, _projectPath?: string, _limit?: number): Promise<SessionLoadMessage[]> {
    return []
  }

  async listPlans(_projectPath: string | undefined, _allProjects: boolean): Promise<PlanDescriptor[]> {
    return []
  }

  async loadPlanContent(_sessionId: string, _projectPath: string, _planToolUseId: string): Promise<string | null> {
    return null
  }

  async listPluginCommands(_workingDirectory: string): Promise<PluginCommandsResult> {
    return { global: [], project: [] }
  }

  async refreshPluginCommands(): Promise<void> {}
}
