import type { DatabaseSync } from 'node:sqlite'

/**
 * The host's hand-written SQLite tables, indexed by `PRAGMA user_version`.
 * These tables exist on every machine whatever its engine: the transcript
 * index, the delivery queues, and host-local settings. Ported domains are
 * generated by drizzle-kit instead (`./sqlite-migrations`).
 *
 * Slot 0 is the baseline every file starts from; a later change appends a
 * slot and never rewrites a released one. A file whose version is past the
 * list predates the baseline and cannot be read.
 */
export const migrations = [
  `
CREATE TABLE automations (
  id TEXT PRIMARY KEY,
  name TEXT,
  enabled INTEGER,
  favorite INTEGER,
  action TEXT,
  trigger_config TEXT,
  next_run_at INTEGER,
  last_run TEXT,
  created_at INTEGER,
  updated_at INTEGER,
  organization_id TEXT NOT NULL DEFAULT 'local'
);

CREATE TABLE automation_runs (
  id TEXT PRIMARY KEY,
  automation_id TEXT NOT NULL REFERENCES automations(id) ON DELETE CASCADE,
  started_at INTEGER,
  finished_at INTEGER,
  status TEXT,
  output TEXT,
  data TEXT
);
CREATE INDEX runs_by_automation ON automation_runs(automation_id, started_at DESC);

-- A pinned manifest is client-global but points at host-scoped sessions. The
-- empty host is a bare id; equal provider ids on two hosts can both be pinned.
CREATE TABLE pinned_sessions (
  session_id TEXT NOT NULL,
  server_id TEXT NOT NULL DEFAULT '',
  provider TEXT,
  title TEXT,
  cwd TEXT,
  pinned_at INTEGER,
  PRIMARY KEY (session_id, server_id)
);

CREATE TABLE projects (
  key TEXT PRIMARY KEY,
  path TEXT,
  folder_name TEXT,
  added_at INTEGER
);

CREATE TABLE recent_projects (
  path TEXT PRIMARY KEY,
  folder_name TEXT,
  last_opened INTEGER
);

CREATE TABLE kv (
  key TEXT PRIMARY KEY,
  value TEXT
);

-- How far the indexer has read each transcript file.
CREATE TABLE session_files (
  path TEXT PRIMARY KEY,
  provider TEXT,
  last_offset INTEGER DEFAULT 0
);

-- The host's index of the provider transcripts on its own disk: what session
-- lists, search, and the runtime read synchronously. The replicated record of
-- a session is \`session_records\`, which lives on the engine's database.
-- Orchestration lineage (parent, root, delegation) rides on the row so every
-- listing receives it without a second lookup. \`server_id\` is set only on
-- the stub a client records when it dispatches a session to another machine.
-- \`viewed_at\` is when the session was last read, so every client agrees.
CREATE TABLE sessions (
  session_id TEXT PRIMARY KEY,
  provider TEXT NOT NULL,
  cwd TEXT,
  project_path TEXT,
  project_root TEXT,
  is_worktree INTEGER,
  slug TEXT,
  first_message TEXT,
  custom_title TEXT,
  last_timestamp INTEGER,
  size INTEGER,
  model TEXT,
  reasoning_effort TEXT,
  branch TEXT,
  server_id TEXT,
  parent_session_id TEXT,
  root_session_id TEXT,
  delegation_exchange_id TEXT,
  delegation_depth INTEGER,
  delegation_intent TEXT,
  delegation_created_at INTEGER,
  viewed_at INTEGER
);
CREATE INDEX sessions_by_parent ON sessions(parent_session_id, last_timestamp DESC);
CREATE INDEX sessions_by_project_root ON sessions(project_root, last_timestamp DESC);
-- PR sync reads the recently active worktree sessions on every tick.
CREATE INDEX sessions_worktree_recent ON sessions(last_timestamp) WHERE is_worktree = 1;

-- Rows are written in transcript order, so the row id is the position. An
-- index on session_id already orders each session's rows by it.
CREATE TABLE session_messages (
  id INTEGER PRIMARY KEY,
  session_id TEXT NOT NULL,
  uuid TEXT,
  role TEXT,
  ts INTEGER,
  text TEXT
);
CREATE INDEX session_messages_by_session ON session_messages(session_id);

CREATE VIRTUAL TABLE session_fts USING fts5(
  text,
  content='session_messages',
  content_rowid='id',
  tokenize='porter unicode61'
);

-- Composer drafts parked for later, scoped to a project. Attachments ride in
-- one JSON column: they are only ever read and written as a whole set.
CREATE TABLE saved_prompts (
  id TEXT PRIMARY KEY,
  project_root TEXT NOT NULL,
  text TEXT NOT NULL,
  attachments TEXT NOT NULL DEFAULT '[]',
  created_at INTEGER NOT NULL
);
CREATE INDEX saved_prompts_by_project ON saved_prompts(project_root, created_at DESC);

-- The host outbox (ADR-0007): durable writes addressed to resources this host
-- cannot reach. \`outbox_ops\` is the queue on the recording host; an op bound
-- for the workspace service is \`destination = 'cloud'\` and carries its
-- delivery seq, and names the organization and the person it is delivered as
-- (plans/010-standard-oauth.md). \`applied_ops\` is the owner-side idempotence
-- guard that makes redelivery harmless.
CREATE TABLE outbox_ops (
  id TEXT PRIMARY KEY,
  domain TEXT NOT NULL,
  resource_id TEXT NOT NULL,
  name TEXT NOT NULL,
  payload TEXT NOT NULL,
  session_id TEXT,
  recorded_at INTEGER NOT NULL,
  state TEXT NOT NULL DEFAULT 'pending',
  error TEXT,
  seq INTEGER,
  destination TEXT NOT NULL DEFAULT 'host',
  organization_id TEXT NOT NULL DEFAULT 'local',
  actor_user_id TEXT NOT NULL DEFAULT '',
  publication_id TEXT
);
CREATE INDEX outbox_ops_by_resource ON outbox_ops(domain, resource_id, id);
CREATE INDEX outbox_ops_by_publication ON outbox_ops(publication_id, state);
CREATE INDEX outbox_ops_by_destination_actor ON outbox_ops(destination, organization_id, actor_user_id, seq);

CREATE TABLE applied_ops (
  op_id TEXT PRIMARY KEY,
  resource_id TEXT NOT NULL,
  applied_at INTEGER NOT NULL
);

-- The identity record of every session: \`session_id\` is the stable Solus id,
-- and each member is one provider thread in order. The unique index makes
-- registration first-writer-wins, and leads with the thread id so a lookup
-- that does not know the provider can seek.
CREATE TABLE session_lineage_members (
  session_id TEXT NOT NULL,
  position INTEGER NOT NULL,
  provider TEXT NOT NULL,
  provider_session_id TEXT,
  cwd TEXT NOT NULL,
  started_at INTEGER NOT NULL,
  ended_at INTEGER,
  updated_at INTEGER NOT NULL,
  PRIMARY KEY (session_id, position)
);
CREATE UNIQUE INDEX session_lineage_member_provider_session
  ON session_lineage_members(provider_session_id, provider)
  WHERE provider_session_id IS NOT NULL;

-- Old provider thread references kept after a worktree fork.
CREATE TABLE session_thread_aliases (
  provider TEXT NOT NULL,
  provider_session_id TEXT NOT NULL,
  session_id TEXT NOT NULL,
  PRIMARY KEY (provider_session_id, provider)
);

-- Saved Insights queries: durable user config, exempt from metrics.db
-- rollover. A row is either a builder QuerySpec (\`spec\`) or editor SQL.
CREATE TABLE saved_metrics_queries (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  form TEXT NOT NULL,
  spec TEXT,
  sql TEXT,
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL
);

-- Named browser profiles: one project, several signed-in identities.
CREATE TABLE browser_profiles (
  project_root TEXT NOT NULL,
  profile_id TEXT NOT NULL,
  name TEXT NOT NULL,
  created_at INTEGER NOT NULL,
  PRIMARY KEY (project_root, profile_id)
);
CREATE TABLE browser_profile_defaults (
  project_root TEXT NOT NULL PRIMARY KEY,
  profile_id TEXT NOT NULL
);

-- Runner delivery (docs/plans/cloud-service-model.md §16): one merged
-- session-record report per session, numbered by the \`kv\` delivery counter.
CREATE TABLE runner_session_reports (
  session_id TEXT PRIMARY KEY,
  seq INTEGER NOT NULL,
  payload TEXT NOT NULL,
  organization_id TEXT NOT NULL DEFAULT 'local',
  actor_user_id TEXT NOT NULL DEFAULT ''
);
CREATE INDEX runner_session_reports_by_destination ON runner_session_reports(organization_id, actor_user_id, seq);

-- The mirror log (docs/plans/cloud-service-model.md §6): what this runner
-- produced and has not yet shipped, in delivery order, per destination.
-- \`transcript_mirror_rows\` and \`activity_mirror_rows\` remember what was
-- already sent, so a pass re-sends only what changed.
CREATE TABLE mirror_log (
  seq INTEGER PRIMARY KEY,
  domain TEXT NOT NULL,
  key TEXT NOT NULL,
  payload TEXT NOT NULL,
  organization_id TEXT NOT NULL DEFAULT 'local',
  actor_user_id TEXT NOT NULL DEFAULT ''
);
CREATE INDEX mirror_log_by_destination ON mirror_log(organization_id, actor_user_id, seq);
CREATE INDEX mirror_log_by_organization ON mirror_log(organization_id, seq);

CREATE TABLE transcript_mirror_rows (
  session_id TEXT NOT NULL,
  position INTEGER NOT NULL,
  hash TEXT NOT NULL,
  PRIMARY KEY (session_id, position)
);

CREATE TABLE activity_mirror_rows (
  session_id TEXT NOT NULL,
  activity_id TEXT NOT NULL,
  PRIMARY KEY (session_id, activity_id)
);

-- Watches (docs/plans/watches.md) wait on the host and then wake one session.
CREATE TABLE watches (
  id TEXT PRIMARY KEY,
  session_id TEXT NOT NULL,
  status TEXT NOT NULL,
  next_run_at INTEGER,
  data TEXT NOT NULL,
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL
);
CREATE INDEX watches_by_session ON watches(session_id, created_at DESC);
CREATE INDEX watches_due ON watches(status, next_run_at);

-- A person's mark on a turn (docs/plans/insights-turn-analysis.md), one per turn.
CREATE TABLE turn_flags (
  trace_id TEXT PRIMARY KEY,
  kind TEXT NOT NULL,
  note TEXT NOT NULL DEFAULT '',
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL
);

-- Codex async questions remain open after the provider turn ends.
CREATE TABLE async_questions (
  question_id TEXT PRIMARY KEY,
  session_id TEXT NOT NULL,
  agent_session_id TEXT NOT NULL,
  questions_json TEXT NOT NULL,
  answers_json TEXT,
  state TEXT NOT NULL DEFAULT 'pending',
  created_at INTEGER NOT NULL
);
CREATE INDEX async_questions_by_session ON async_questions(session_id, state, created_at);
CREATE INDEX async_questions_by_agent ON async_questions(agent_session_id, state, created_at);

-- The recoverable operation that moves a Local resource into one organization
-- on Share or Move (docs/plans/organization-scope.md §7).
CREATE TABLE publications (
  id TEXT PRIMARY KEY,
  resource_kind TEXT NOT NULL,
  resource_id TEXT NOT NULL,
  organization_id TEXT NOT NULL,
  actor_user_id TEXT NOT NULL,
  state TEXT NOT NULL,
  fingerprint TEXT,
  through_seq INTEGER,
  error TEXT,
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL
);
CREATE UNIQUE INDEX publications_active_resource ON publications(resource_kind, resource_id) WHERE state IN ('pending', 'sent');
CREATE INDEX publications_by_resource ON publications(resource_kind, resource_id, created_at DESC);
`,
  // Session match (docs/plans/unified-search.md §1, §4). A message row id is
  // its session's number times 2^20 plus its position, so a hit names its
  // session with no join; the index follows the word rule, with no stemmer.
  // The messages are read again from the transcripts: every Claude file is
  // read from its start, and the Codex refresh reads every thread again.
  `
DROP TABLE session_fts;
DROP TABLE session_messages;

CREATE TABLE session_keys (
  number INTEGER PRIMARY KEY,
  session_id TEXT NOT NULL UNIQUE
);

CREATE TABLE session_messages (
  id INTEGER PRIMARY KEY,
  session_id TEXT NOT NULL,
  uuid TEXT,
  role TEXT,
  ts INTEGER,
  text TEXT
);
CREATE INDEX session_messages_by_session ON session_messages(session_id);

CREATE VIRTUAL TABLE session_fts USING fts5(
  text,
  content='session_messages',
  content_rowid='id',
  tokenize='unicode61'
);

DELETE FROM session_files;
DELETE FROM kv WHERE key = 'codex-session-index-watermark';
INSERT INTO kv(key, value) VALUES ('session-messages-rebuild', '1')
  ON CONFLICT(key) DO UPDATE SET value = excluded.value;
`,
  // The notifications hub's host-local table (plans/015-notifications-hub.md):
  // the pull request observer's baseline.
  `
-- The last complete answer of the code host about the pull requests that ask
-- one person's attention: per credential (provider host and viewer login),
-- repository, and recipient. Only a complete answer replaces it.
CREATE TABLE notification_pr_observations (
  authority TEXT NOT NULL,
  repo TEXT NOT NULL,
  recipient_key TEXT NOT NULL,
  pending TEXT NOT NULL,
  observed_at INTEGER NOT NULL,
  PRIMARY KEY (authority, repo, recipient_key)
);
`,
  // v1 of the notifications hub queued automation results here; v2 writes them
  // in the run's own transaction. A file that ran v1's slot above has the table.
  `
DROP TABLE IF EXISTS notification_intents;
`,
  // Execution recovery belongs to this host even when records are mirrored.
  `
CREATE TABLE session_restart_runs (
  session_id TEXT PRIMARY KEY,
  organization_id TEXT NOT NULL DEFAULT 'local',
  run_id TEXT NOT NULL,
  state TEXT NOT NULL,
  payload TEXT NOT NULL,
  updated_at INTEGER NOT NULL
);
`,
  // The run ledger (docs/plans/orchestration-queue.md): queue entries,
  // exchanges, and restart receipts in one host-local file, so one transaction
  // can change them together. Restart receipts move from the table above; the
  // JSON receipts of earlier versions are imported by the ledger on boot.
  `
CREATE TABLE runs (
  session_id TEXT PRIMARY KEY,
  run_id TEXT NOT NULL,
  state TEXT NOT NULL,
  payload TEXT NOT NULL,
  updated_at INTEGER NOT NULL
);
INSERT INTO runs(session_id, run_id, state, payload, updated_at)
  SELECT session_id, run_id, state, payload, updated_at FROM session_restart_runs;
DROP TABLE session_restart_runs;

CREATE TABLE run_queue (
  queue_id TEXT PRIMARY KEY,
  session_id TEXT NOT NULL,
  position INTEGER NOT NULL,
  payload TEXT NOT NULL,
  updated_at INTEGER NOT NULL
);
CREATE INDEX run_queue_by_session ON run_queue(session_id, position);

CREATE TABLE run_exchanges (
  exchange_id TEXT PRIMARY KEY,
  sender_session_id TEXT NOT NULL,
  target_session_id TEXT NOT NULL,
  run_id TEXT,
  state TEXT NOT NULL,
  delivery_state TEXT,
  delivery_queue_id TEXT,
  payload TEXT NOT NULL,
  report TEXT,
  reply TEXT,
  settled_at INTEGER,
  updated_at INTEGER NOT NULL
);
`,
]

export function runMigrations(db: DatabaseSync): void {
  // SAFETY: SQLite PRAGMA user_version always returns one row with this integer column.
  const row = db.prepare('PRAGMA user_version').get() as { user_version: number }
  const currentVersion = row.user_version
  if (currentVersion > migrations.length) {
    throw new Error('solus.db predates the current schema. Delete solus.db (and its -wal and -shm files) in the Solus data directory; it is recreated empty.')
  }

  for (let index = currentVersion; index < migrations.length; index++) {
    db.exec('BEGIN IMMEDIATE')
    try {
      db.exec(migrations[index])
      db.exec(`PRAGMA user_version = ${index + 1}`)
      db.exec('COMMIT')
    } catch (error) {
      db.exec('ROLLBACK')
      throw error
    }
  }
}
