import type { RpcMethod } from './rpc'

/**
 * Which plane each RPC method belongs to (docs/plans/cloud-service-model.md).
 *
 * - `collaboration`  the records people share and read together: tasks, works,
 *                    comments, shares, presence, session records and history,
 *                    pull-request records, automation definitions, notifications,
 *                    seat status, and the host's identity and settings a client
 *                    asks for first.
 * - `execution`      what needs a checkout and an agent process: prompting,
 *                    permissions, git, files, diffs, worktrees, project config,
 *                    checkout-bound review, setup, seat connection, and the
 *                    machine's own window, updates, and browser.
 *
 * Every method has exactly one plane; a host serves the planes its roles name
 * and refuses the rest with `PLANE_DISABLED`.
 */
export type RpcPlane = 'collaboration' | 'execution'

export const RPC_PLANES = {
  // Lifecycle / window
  start: 'execution',
  isVisible: 'execution',
  getAppGlobalShortcuts: 'execution',
  setAppGlobalShortcuts: 'execution',
  restartApp: 'execution',
  serverGetCapabilities: 'collaboration',

  // Sessions / agent
  watchSession: 'execution',
  unwatchSession: 'execution',
  prompt: 'execution',
  retry: 'execution',
  stopSession: 'execution',
  resetSession: 'execution',
  switchSessionAgent: 'execution',
  createHeadlessSession: 'execution',
  promptSession: 'execution',

  // Permission / interaction
  respondPermission: 'execution',
  respondQuestion: 'execution',
  rateLimitDecision: 'execution',
  cancelQueuedPrompt: 'execution',
  editQueuedPrompt: 'execution',
  writePlanFile: 'execution',
  rewindFiles: 'execution',

  // Files / media
  saveFileDialog: 'execution',
  openExternal: 'execution',
  openInFileManager: 'execution',
  openInTerminal: 'execution',
  openWorktreeTerminal: 'execution',
  resolveTerminal: 'execution',
  attachFiles: 'execution',
  attachFilePaths: 'execution',
  attachUpload: 'execution',
  assetUpload: 'execution',
  assetCreateUrl: 'execution',
  takeScreenshot: 'execution',
  pasteImage: 'execution',
  transcribeAudio: 'execution',
  warmTranscription: 'execution',
  voiceModelStatus: 'execution',
  voiceModelRetry: 'execution',
  logVoiceTranscription: 'execution',
  searchFiles: 'execution',
  searchProjectContents: 'execution',
  listDirectory: 'execution',
  createDirectory: 'execution',
  readProjectFile: 'execution',
  listProjectFiles: 'execution',
  mutateProjectFile: 'execution',
  writeFile: 'execution',
  updateAgentFiles: 'execution',

  // Code intelligence
  codeIntelSymbolAt: 'execution',
  codeIntelReferences: 'execution',
  codeIntelDocs: 'execution',
  codeIntelStatus: 'execution',
  codeIntelInstall: 'execution',
  codeIntelReindex: 'execution',

  // Sessions / plans / projects
  bindRuntimeSession: 'execution',
  listSessions: 'collaboration',
  searchSessions: 'collaboration',
  loadSession: 'collaboration',
  loadSessionPage: 'collaboration',
  loadSessionToolInputs: 'collaboration',
  loadSessionPreview: 'collaboration',
  loadSessionMessageWindow: 'collaboration',
  getSessionInfo: 'collaboration',
  getSessionInfos: 'collaboration',
  resolveSessionLineage: 'collaboration',
  describeSession: 'collaboration',
  generateSessionMetadata: 'collaboration',
  setSessionTitle: 'collaboration',
  setSessionBranch: 'collaboration',
  listRecentProjects: 'execution',
  trackRecentProject: 'execution',
  listPlans: 'collaboration',
  loadPlanContent: 'collaboration',
  getThreadGoal: 'collaboration',
  setThreadGoal: 'collaboration',
  clearThreadGoal: 'collaboration',
  loadPlanAnnotations: 'collaboration',
  savePlanAnnotations: 'collaboration',
  toggleBookmarkPlan: 'collaboration',

  // Editor integration
  detectEditors: 'execution',
  openInEditor: 'execution',

  // Plugins
  getPluginCommands: 'execution',

  // Worktree / diff / git
  worktreeListProject: 'execution',
  diff: 'execution',
  diffFileContents: 'execution',
  diffStats: 'execution',
  listTurnSnapshots: 'execution',
  gitRunAction: 'execution',
  gitDiscard: 'execution',
  gitSync: 'execution',
  gitCheckoutBranch: 'execution',
  worktreeBranches: 'execution',
  worktreeRestore: 'execution',
  continueInWorktree: 'execution',
  gitRefreshState: 'execution',
  gitIdentity: 'execution',
  gitRegisterEnvironment: 'execution',
  gitRepositoryStatus: 'execution',
  gitInitRepository: 'execution',
  githubPublishRepository: 'execution',
  projectConfigLoad: 'execution',
  projectConfigSave: 'execution',
  listProjects: 'execution',
  listProjectIdentities: 'execution',
  resolveDispatchHistoryRoots: 'execution',
  deleteProject: 'execution',

  // Skills
  skillsSearch: 'execution',
  skillsInstall: 'execution',
  skillsList: 'execution',
  skillsRemove: 'execution',

  // Pinned sessions, read state, activity, saved prompts
  pinnedSessionsList: 'collaboration',
  togglePinnedSession: 'collaboration',
  setSessionReadState: 'collaboration',
  activityLease: 'collaboration',
  savedPromptsList: 'collaboration',
  savedPromptsCreate: 'collaboration',
  savedPromptsDelete: 'collaboration',

  // Design mode
  enterDesignMode: 'execution',
  designModeReady: 'execution',
  exitDesignMode: 'execution',
  submitDesignAnnotations: 'execution',

  // Connections
  connectionsListEndpoints: 'collaboration',
  connectionsGeneratePairToken: 'collaboration',
  connectionsListSessions: 'collaboration',
  connectionsBootstrapDiscoveredServer: 'collaboration',
  connectionsRevokeDevice: 'collaboration',
  connectionsGetServerInfo: 'collaboration',
  connectionsSetRemoteAccess: 'collaboration',
  connectionsSetTrustLocalNetwork: 'collaboration',

  // Personal Uplink
  uplinkLink: 'collaboration',
  uplinkUnlink: 'collaboration',
  uplinkStatus: 'collaboration',

  // Sharing
  shareGet: 'collaboration',
  shareSet: 'collaboration',
  shareSetLink: 'collaboration',
  shareTransfer: 'collaboration',

  // Provider seats: status is a record, connecting is a login on the machine
  seatList: 'collaboration',
  seatConnectStart: 'execution',
  seatConnectSubmitCode: 'execution',
  seatConnectCancel: 'execution',
  seatConnectToken: 'execution',
  seatDisconnect: 'collaboration',
  seatRemove: 'collaboration',

  // Presence
  presenceSnapshot: 'collaboration',
  presenceSetFocus: 'collaboration',
  presenceSetComposing: 'collaboration',
  setAnalyticsConsent: 'collaboration',

  // Host config
  typeSafeKeySet: 'collaboration',
  configGet: 'collaboration',
  configUpdate: 'collaboration',
  textGenerationSettingsGet: 'collaboration',
  otelSettingsGet: 'collaboration',
  discoverServers: 'collaboration',
  getServerCapabilities: 'collaboration',
  setProjectsBaseDirectory: 'execution',
  setupInstallAgentCli: 'execution',
  setupCheckAgentAuth: 'execution',
  setupListGithubRepos: 'execution',
  setupPrepareProject: 'execution',
  setupCloneProject: 'execution',
  setupSyncProject: 'execution',
  setupAdoptProject: 'execution',
  setupHostReadiness: 'execution',
  setupInstallGit: 'execution',
  setupInstallGh: 'execution',
  setupSetGitIdentity: 'execution',
  setupCheckSshAccess: 'execution',
  setupAuthorizeGhCli: 'execution',
  setupInstallGitCredentialHelper: 'execution',

  // Host and provider updates
  hostUpdateStatus: 'execution',
  hostCheckForUpdates: 'execution',
  hostInstallUpdate: 'execution',
  hostCancelUpdate: 'execution',

  // Attention and push notifications
  listAttention: 'collaboration',
  pushGetPublicKey: 'collaboration',
  pushSubscribe: 'collaboration',
  pushUnsubscribe: 'collaboration',

  // Folio / works
  createWork: 'collaboration',
  saveWork: 'collaboration',
  loadWork: 'collaboration',
  listWorks: 'collaboration',
  deleteWork: 'collaboration',
  duplicateWork: 'collaboration',
  linkWorkSession: 'collaboration',
  promoteWorkToProject: 'collaboration',
  loadWorkAnnotations: 'collaboration',
  applyWorkComment: 'collaboration',
  markWorkCommentRead: 'collaboration',
  readWorkGoogleComments: 'collaboration',
  refreshWorkGoogleComments: 'collaboration',
  sendWorkGoogleComment: 'collaboration',
  readWorkExternalComments: 'collaboration',
  refreshWorkExternalComments: 'collaboration',
  sendWorkExternalComment: 'collaboration',
  agentSaveWork: 'collaboration',
  loadWorkPrevious: 'collaboration',
  revertWork: 'collaboration',
  setWorkPinned: 'collaboration',

  // Upstream doc mirror
  docProviderStatuses: 'collaboration',
  docDestinations: 'collaboration',
  publishWork: 'collaboration',
  pullWorkUpstream: 'collaboration',
  refreshWorkUpstream: 'collaboration',
  unlinkWorkUpstream: 'collaboration',
  publishPlan: 'collaboration',
  pullPlanUpstream: 'collaboration',
  refreshPlanUpstream: 'collaboration',
  unlinkPlanUpstream: 'collaboration',
  importDocFromUrl: 'collaboration',

  // Google Drive
  googleStatus: 'collaboration',
  googleConnect: 'collaboration',
  googleDisconnect: 'collaboration',

  // Cloudflare deployment credentials
  cloudflareStatus: 'execution',
  cloudflareConnect: 'execution',
  cloudflareDisconnect: 'execution',

  // Atlassian
  atlassianStatus: 'collaboration',
  atlassianStartOAuth: 'collaboration',
  atlassianCancelOAuth: 'collaboration',
  atlassianDisconnect: 'collaboration',
  atlassianJiraProjects: 'collaboration',

  // Git provider auth
  providerStatus: 'execution',
  providerConnect: 'execution',
  providerCancelConnect: 'execution',
  providerDisconnect: 'execution',
  githubExportCredential: 'execution',
  providerViewer: 'execution',

  // PR records
  prList: 'collaboration',
  prNeedsReview: 'collaboration',
  prGetEfforts: 'collaboration',
  prGuideMetadata: 'collaboration',
  prOpenReview: 'execution',
  prGetDiff: 'execution',
  prGetDiffFileContents: 'execution',
  prPrepareCheckout: 'execution',
  prGetDetail: 'collaboration',
  prUpdate: 'collaboration',
  prGetOverview: 'collaboration',
  prChangedFiles: 'collaboration',
  prListThreads: 'collaboration',
  prListComments: 'collaboration',
  prListCommits: 'collaboration',
  prListReviewers: 'collaboration',
  prListReviewerCandidates: 'collaboration',
  prRequestReviewers: 'collaboration',
  prRemoveRequestedReviewer: 'collaboration',
  prListLabelCandidates: 'collaboration',
  prSetLabels: 'collaboration',
  prUpdateLifecycle: 'collaboration',
  prSubmitReview: 'collaboration',
  prAddIssueComment: 'collaboration',
  prDeleteIssueComment: 'collaboration',
  prInterdiff: 'execution',
  prReplyThread: 'collaboration',
  prResolveThread: 'collaboration',
  prUnresolveThread: 'collaboration',
  prGenerateGuides: 'execution',
  prMerge: 'collaboration',
  prPrepareConflictResolution: 'execution',
  prInvalidate: 'collaboration',

  // Review guide (checkout-bound)
  readLedger: 'execution',
  writeLedger: 'execution',
  getReviewContext: 'execution',
  generateGuide: 'execution',
  requestReviewGuide: 'execution',
  reviewGuideStatus: 'execution',
  sessionGuideStatuses: 'execution',
  cancelGenerateGuide: 'execution',
  readGuide: 'execution',
  readReviewState: 'execution',
  writeReviewState: 'execution',

  // Tasks
  tasksProviderStatus: 'collaboration',
  inboxListUpstream: 'collaboration',
  tasksListUpstream: 'collaboration',
  tasksGetUpstream: 'collaboration',
  tasksUpdateUpstream: 'collaboration',
  tasksCommentUpstream: 'collaboration',
  tasksListAssigneeCandidates: 'collaboration',
  tasksListCandidates: 'collaboration',
  tasksImport: 'collaboration',
  tasksPublish: 'collaboration',
  tasksSyncNow: 'collaboration',
  tasksList: 'collaboration',
  tasksSidebarSnapshot: 'collaboration',
  tasksGet: 'collaboration',
  tasksCreate: 'collaboration',
  tasksUpdate: 'collaboration',
  tasksMarkRead: 'collaboration',
  tasksRecordActivity: 'collaboration',
  tasksDelete: 'collaboration',
  tasksComment: 'collaboration',
  tasksDeleteComment: 'collaboration',
  tasksPublishComments: 'collaboration',
  tasksLinkSession: 'collaboration',
  tasksUnlinkSession: 'collaboration',
  tasksRekeySession: 'collaboration',
  tasksSessions: 'collaboration',
  tasksForSession: 'collaboration',
  tasksPrepareForSession: 'collaboration',
  tasksSnapshot: 'collaboration',
  tasksLink: 'collaboration',
  tasksUnlink: 'collaboration',
  tasksLinkedTo: 'collaboration',
  tasksAttachArtifact: 'collaboration',

  // Host outbox
  outboxList: 'collaboration',
  outboxAck: 'collaboration',
  outboxApply: 'collaboration',

  // Automations: definitions and history are records, a run needs a machine
  automationCreate: 'collaboration',
  automationList: 'collaboration',
  automationRead: 'collaboration',
  automationUpdate: 'collaboration',
  automationDelete: 'collaboration',
  automationSetEnabled: 'collaboration',
  automationRun: 'execution',
  automationCancel: 'execution',
  automationListRuns: 'collaboration',
  automationReadRun: 'collaboration',

  // PR stacks and checks
  stackGet: 'collaboration',
  stackDetect: 'collaboration',
  stackAddManualEdge: 'collaboration',
  stackRemoveManualEdge: 'collaboration',
  prChecks: 'collaboration',
  prChecksActivity: 'collaboration',

  // Subscription quota per agent provider
  usageLimits: 'execution',

  // Browser
  browserListTargets: 'execution',
  browserListPages: 'execution',
  browserOpen: 'execution',
  browserClose: 'execution',
  browserNavigate: 'execution',
  browserSetViewport: 'execution',
  browserSetAppearance: 'execution',
  browserSnapshot: 'execution',
  browserInteract: 'execution',
  browserAttachSurface: 'execution',
  browserDetachSurface: 'execution',
  browserReportSurface: 'execution',
  browserClearProfile: 'execution',
  browserSubscribeFrames: 'execution',
  browserUnsubscribeFrames: 'execution',
  browserCaptureEvidence: 'execution',
  browserEvidenceOptions: 'execution',
  browserOpenDevTools: 'execution',
  browserSetAnnotationTool: 'execution',
  browserAnnotationState: 'execution',
  browserAnnotate: 'execution',
  browserListProfiles: 'execution',
  browserCreateProfile: 'execution',
  browserRenameProfile: 'execution',
  browserDeleteProfile: 'execution',
  browserSetDefaultProfile: 'execution',
  browserListCookieSources: 'execution',
  browserRequestCookieAccess: 'execution',
  browserImportCookies: 'execution',

  // Observability / Insights over the host's own metrics database
  metricsQuery: 'execution',
  metricsRunSql: 'execution',
  metricsTurnPage: 'execution',
  metricsValidateSql: 'execution',
  metricsCompileNl: 'execution',
  metricsSchema: 'execution',
  metricsDistinctValues: 'execution',
  metricsListSavedQueries: 'execution',
  metricsSaveQuery: 'execution',
  metricsDeleteQuery: 'execution',
  metricsSessionSummary: 'execution',
  metricsTurnTrace: 'execution',
  logFilePath: 'execution',
} as const satisfies Record<RpcMethod, RpcPlane>

export function rpcPlaneOf(method: RpcMethod): RpcPlane {
  return RPC_PLANES[method]
}
