-- Generated by proof.test.mjs; fixture values only.
-- Run schema.sql first in a disposable SQLite database.
-- 3 data statements + one BEGIN/COMMIT pair; 2 commit boundaries.

-- acceptRunning
INSERT INTO session_message (message_id, command_key, actor_user_id, request_fingerprint, kind, mode,
    sender_session_id, recipient_session_id, reply_session_id, text, options_json,
    source_message_id, state, attempt_no, seat_user_id, provider, execution_json, created_at, started_at)
    VALUES ('M1', 'C1', 'owner', 'cda5548af7a08efb9105f81b2a1267c40d7aafedec76a930103bbc4a7851a008', 'instruction', 'auto', 'parent', 'child', 'parent', 'Build the login API', '{}', NULL, 'running', 1, 'owner', 'codex', '{"cwd":"/disposable/project","model":"fixture-model","permissionMode":"ask"}', 100, 100)
    ON CONFLICT (actor_user_id, command_key) DO NOTHING
    RETURNING message_id;

-- BEGIN IMMEDIATE
BEGIN IMMEDIATE;

-- settle
UPDATE session_message
    SET state = 'completed', result_text = 'API built', error_text = NULL, provider_thread_id = 'provider-thread', provider_turn_id = 'provider-M1', settled_at = 130
    WHERE message_id = 'M1' AND state = 'running'
    RETURNING message_id;

-- reply
INSERT INTO session_message (message_id, command_key, actor_user_id, request_fingerprint, kind, mode,
    sender_session_id, recipient_session_id, reply_session_id, text, options_json,
    source_message_id, state, attempt_no, seat_user_id, provider, execution_json, created_at, started_at)
    SELECT DISTINCT 'result:' || turn.message_id || ':' || waiting.reply_session_id,
      'result:' || turn.message_id || ':' || waiting.reply_session_id,
      turn.actor_user_id, 'result-of:' || turn.message_id, 'result', 'auto',
      turn.recipient_session_id, waiting.reply_session_id, NULL, NULL, '{}',
      turn.message_id, 'queued', 0, NULL, NULL, NULL, 130, NULL
    FROM session_message turn
    JOIN session_message waiting
      ON waiting.message_id = turn.message_id OR waiting.consumed_by_message_id = turn.message_id
    WHERE turn.message_id = 'M1' AND turn.state IN ('completed', 'failed', 'cancelled')
      AND waiting.reply_session_id IS NOT NULL
    RETURNING message_id, recipient_session_id;

-- COMMIT
COMMIT;
