-- Generated by proof.test.mjs; fixture values only.
-- Run schema.sql first in a disposable SQLite database.
-- Delegation round trip with an idle parent: 4 data statements, 3 commits, two turns.

-- insert
INSERT INTO session_message (message_id, actor_user_id, seat_user_id, kind, sender_session_id,
    recipient_session_id, reply_session_id, text, options_json, source_message_id,
    consumed_by_message_id, state, attempt_no, provider, execution_json, created_at, started_at, settled_at)
    VALUES ('M1', 'owner', 'owner', 'instruction', 'parent', 'child', 'parent', 'Build the login API', '{}', NULL, NULL, 'running', 1, 'codex', '{"cwd":"/disposable/project","model":"fixture-model","permissionMode":"ask"}', 100, 100, NULL)
    ON CONFLICT (message_id) DO NOTHING
    RETURNING message_id;

-- BEGIN IMMEDIATE
BEGIN IMMEDIATE;

-- settle
INSERT INTO session_message (message_id, actor_user_id, seat_user_id, kind,
      sender_session_id, recipient_session_id, reply_session_id, text, options_json,
      state, attempt_no, provider, execution_json, provider_thread_id, provider_turn_id,
      result_text, error_text, created_at, started_at, settled_at)
    VALUES ('M1', 'owner', 'owner', 'instruction', 'parent', 'child', NULL, 'Build the login API', '{}', 'completed', 1, 'codex', '{"cwd":"/disposable/project","model":"fixture-model","permissionMode":"ask"}', 'provider-thread', 'provider-M1', 'API built', NULL, 100, 100, 130)
    ON CONFLICT (message_id) DO UPDATE SET
      state = excluded.state, provider_thread_id = excluded.provider_thread_id,
      provider_turn_id = excluded.provider_turn_id, result_text = excluded.result_text,
      error_text = excluded.error_text, settled_at = excluded.settled_at
    WHERE session_message.state = 'running'
    RETURNING message_id;

-- insert
INSERT INTO session_message (message_id, actor_user_id, seat_user_id, kind, sender_session_id,
    recipient_session_id, reply_session_id, text, options_json, source_message_id,
    consumed_by_message_id, state, attempt_no, provider, execution_json, created_at, started_at, settled_at)
    VALUES ('result:M1:parent', 'owner', 'owner', 'result', 'child', 'parent', NULL, NULL, '{}', 'M1', NULL, 'running', 1, 'codex', '{"cwd":"/disposable/project","model":"fixture-model","permissionMode":"ask"}', 130, 130, NULL)
    ON CONFLICT (message_id) DO NOTHING
    RETURNING message_id;

-- COMMIT
COMMIT;

-- settle
INSERT INTO session_message (message_id, actor_user_id, seat_user_id, kind,
      sender_session_id, recipient_session_id, reply_session_id, text, options_json,
      state, attempt_no, provider, execution_json, provider_thread_id, provider_turn_id,
      result_text, error_text, created_at, started_at, settled_at)
    VALUES ('result:M1:parent', 'owner', 'owner', 'instruction', NULL, 'parent', NULL, NULL, '{}', 'completed', 1, 'codex', '{"cwd":"/disposable/project","model":"fixture-model","permissionMode":"ask"}', 'provider-thread', 'provider-result:M1:parent', 'Reviewed', NULL, 130, 130, 130)
    ON CONFLICT (message_id) DO UPDATE SET
      state = excluded.state, provider_thread_id = excluded.provider_thread_id,
      provider_turn_id = excluded.provider_turn_id, result_text = excluded.result_text,
      error_text = excluded.error_text, settled_at = excluded.settled_at
    WHERE session_message.state = 'running'
    RETURNING message_id;
