/**
 * Writes `generated-uniwind-theme.css`: T3 Code's token set (`--color-*`)
 * derived from the Solus palette, for the light and dark uniwind themes.
 * Run after changing `src/theme/theme-colors.ts` or `mobile-theme.ts`:
 *
 *   bun apps/mobile/scripts/generate-uniwind-theme.ts
 */
import { writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { getMobileThemeVariables } from '../src/lib/mobileTheme'

const block = (appearance: 'light' | 'dark') => {
  const variables = getMobileThemeVariables(appearance)
  const lines = Object.entries(variables).map(([name, value]) => `      ${name}: ${value};`)
  return `    @variant ${appearance} {\n${lines.join('\n')}\n    }`
}

const css = `/* Generated by scripts/generate-uniwind-theme.ts. Do not edit by hand. */
@layer theme {
  :root {
${block('light')}
${block('dark')}
  }
}
`
writeFileSync(join(import.meta.dir, '..', 'generated-uniwind-theme.css'), css)
